### ISSUE TITLE
Crash:  Couldn't load mupdf from loader 

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/android#255]
@intrications This was reported 3 mn after #254 by same user

```
APP_VERSION_CODE=31
APP_VERSION_NAME=1.3.0
ANDROID_VERSION=4.3
PHONE_MODEL=C1905
CUSTOM_DATA=
STACK_TRACE=java.lang.UnsatisfiedLinkError: Couldn't load mupdf from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.prestedit.chevalmag-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.prestedit.chevalmag-2, /vendor/lib, /system/lib]]]: findLibrary returned null
at java.lang.Runtime.loadLibrary(Runtime.java:355)
at java.lang.System.loadLibrary(System.java:525)
at com.artifex.mupdf.MuPDFCore.(MuPDFCore.java:17)
at com.librelio.lib.utils.PDFParser.(PDFParser.java:31)
at com.librelio.activity.MuPDFActivity.openFile(MuPDFActivity.java:606)
at com.librelio.activity.MuPDFActivity.getMuPdfCore(MuPDFActivity.java:169)
at com.librelio.activity.MuPDFActivity.onCreate(MuPDFActivity.java:111)
at android.app.Activity.performCreate(Activity.java:5133)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2311)
at android.app.ActivityThread.access$600(ActivityThread.java:149)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5214)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
at dalvik.system.NativeStart.main(Native Method)

LOGCAT=07-25 01:15:07.113 D/QCNEA (29531): |CAC| Connected to server socket: 77
07-25 01:15:07.113 I/QCNEA (29531): |CAC| [CNE CLIENT STATE MACHINE] transition CONNECTING -> CONNECTED_PENDING_PERM_RESPONSE
07-25 01:15:07.113 D/QCNEA (29531): |CAC| In monitor thread, performing select
07-25 01:15:07.113 D/QCNEA (29531): |CAC| readCallback: read len:12, ret:0, errno:0
07-25 01:15:07.113 I/QCNEA (29531): |CAC| [CNE CLIENT STATE MACHINE] transition CONNECTED_PENDING_PERM_RESPONSE -> NOT_CONNECTED_ACCESS_DENIED
07-25 01:15:07.113 D/QCNEA (29531): |CAC| readCallback: read len:0, ret:0, errno:0
07-25 01:15:07.113 E/QCNEA (29531): |CAC| readCallback: end of stream
07-25 01:15:07.113 V/QCNEA (29531): |CAC| Dispatching Latency Service Status Update [status:SERVICE_STOPPED]
07-25 01:15:07.113 V/QCNEA (29531): |CAC| Dispatching Bitrate Service Status Update [status:SERVICE_STOPPED]
07-25 01:15:07.113 V/QCNEA (29531): |CAC| Clients reset
07-25 01:15:07.113 D/QCNEA (29531): |CAC| Monitor loop is terminating
07-25 01:15:07.113 I/QCNEA (29531): |CAC| client permission denied.
07-25 01:15:07.113 D/TCPFinAggregation(29531): Failed to get network status! received ret: -6
07-25 01:15:07.113 D/Socket_Pool(29531): netstack: CloseUnusedSockets is ON
07-25 01:15:07.113 D/Socket_Pool(29531): netstack: system net.statistics value: 0
07-25 01:15:07.113 D/Socket_Pool(29531): netstack: CloseUnusedSockets is ON
07-25 01:15:07.113 D/Socket_Pool(29531): netstack: system net.statistics value: 0
07-25 01:15:07.123 D/netstack(29531): netstack: Request Priority is ON
07-25 01:15:07.123 D/ (29531): external/chromium/net/http/http_getzip_factory.cc: libgetzip.so successfully loaded
07-25 01:15:07.123 D/ (29531): external/chromium/net/http/http_getzip_factory.cc,: GETzip initializing method was found in libgetzip.so
07-25 01:15:07.123 D/ (29531): netstack: Getzip is: ON, Version: 5.0.1
07-25 01:15:07.143 W/Settings(29531): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
07-25 01:15:07.154 D/ (29531): netstack: Early Connections is: ON, Version: 5.0.1, Param: 3
07-25 01:15:07.154 I/ (29531): netstack: LIB_MGR - Lib loaded: qnet-plugin.so
07-25 01:15:07.154 D/ (29531): netstack: Caching Of Redirection is: ON, Version: 5.0.1
07-25 01:15:07.184 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.184 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.184 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.184 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.184 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.184 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.184 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.184 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.194 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.194 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.194 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.194 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.214 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.214 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.214 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.214 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.214 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.214 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.254 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.254 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.274 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.274 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.274 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.274 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.284 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.284 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.284 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.284 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.784 D/-heap (29531): GC_FOR_ALLOC freed 3174K, 22% free 11817K/15128K, paused 25ms, total 25ms
07-25 01:15:07.914 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.914 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.914 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.914 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.924 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.924 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.924 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.924 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.924 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.924 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.934 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.934 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.934 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.934 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.934 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.934 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.934 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.934 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.964 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.964 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.964 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.964 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.964 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.964 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.964 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.964 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:07.994 D/Event (29531): No subscripers registered for event class com.librelio.event.ChangeInDownloadedMagazinesEvent
07-25 01:15:07.994 D/Event (29531): No subscripers registered for event class de.greenrobot.event.NoSubscriberEvent
07-25 01:15:08.605 I/qtaguid (29531): Failed write_ctrl(t 107 43787191582720 7471215) res=-1 errno=1
07-25 01:15:08.605 I/qtaguid (29531): Tagging socket 107 with tag 27d300000000(10195) for uid 7471215 failed errno=-1
07-25 01:15:08.615 I/qtaguid (29531): Failed write_ctrl(t 109 43787191582720 7471215) res=-1 errno=1
07-25 01:15:08.615 I/qtaguid (29531): Tagging socket 109 with tag 27d300000000(10195) for uid 7471215 failed errno=-1
07-25 01:15:08.615 I/qtaguid (29531): Failed write_ctrl(t 113 43787191582720 7471215) res=-1 errno=1
07-25 01:15:08.615 I/qtaguid (29531): Tagging socket 113 with tag 27d300000000(10195) for uid 7471215 failed errno=-1
07-25 01:15:08.675 W/webcore (29531): skip viewSizeChanged as w is 0
07-25 01:15:08.675 E/cutils-trace(29531): Error opening trace file: No such file or directory (2)
07-25 01:15:09.096 D/MagazineAdapter(29531): test: true true
07-25 01:15:09.306 D/MuPDFActivity(29531): Trying to open /data/data/com.prestedit.chevalmag/app_librelio/cm513_20140724/cm513_20140724.pdf
07-25 01:15:09.306 W/dalvikvm(29531): Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/artifex/mupdf/MuPDFCore;
07-25 01:15:09.306 D/AndroidRuntime(29531): Shutting down VM
07-25 01:15:09.306 W/dalvikvm(29531): threadid=1: thread exiting with uncaught exception (group=0x41ef08b0)
07-25 01:15:09.316 W/GAV2 (29531): Thread[main,5,main]: dispatch call queued. Need to call GAServiceManager.getInstance().initialize().
07-25 01:15:09.316 E/ACRA (29531): ACRA caught a UnsatisfiedLinkError exception for com.prestedit.chevalmag. Building report.
07-25 01:15:09.316 D/ACRA (29531): Using custom Report Fields
07-25 01:15:09.326 I/ACRA (29531): READ_LOGS granted! ACRA can include LogCat and DropBox data.
07-25 01:15:09.366 D/ACRA (29531): Retrieving logcat output...
```

**Comment by ammaratef45** [comment]
I had the same crash using my emulator, It has API 19 and x86 processor
The full error report in the logcat is following

E/AndroidRuntime( 2464): FATAL EXCEPTION: main
E/AndroidRuntime( 2464): Process: com.artifex.mupdfdemo, PID: 2464
E/AndroidRuntime( 2464): java.lang.UnsatisfiedLinkError: Couldn't load mupdf_java32 from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.artifex.mupdfdemo-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.artifex.mupdfdemo-2, /system/lib]]]: findLibrary returned null
E/AndroidRuntime( 2464): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
E/AndroidRuntime( 2464): 	at java.lang.System.loadLibrary(System.java:526)
E/AndroidRuntime( 2464): 	at com.artifex.mupdfdemo.MuPDFCore.<clinit>(MuPDFCore.java:15)
E/AndroidRuntime( 2464): 	at com.artifex.mupdfdemo.MuPDFActivity.openFile(MuPDFActivity.java:229)
E/AndroidRuntime( 2464): 	at com.artifex.mupdfdemo.MuPDFActivity.onCreate(MuPDFActivity.java:359)
E/AndroidRuntime( 2464): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 2464): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 2464): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
E/AndroidRuntime( 2464): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
E/AndroidRuntime( 2464): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 2464): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 2464): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2464): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2464): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 2464): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2464): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2464): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 2464): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 2464): 	at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager( 1571):   Force finishing activity com.artifex.mupdfdemo/.MuPDFActivity
W/ActivityManager( 1571):   Force finishing activity com.artifex.mupdfdemo/.ChoosePDFActivity
